/**
 * settle-game.ts — Node.js example for backend integration
 *
 * Demonstrates the full flow:
 *   1. Create a game (escrow PDA)
 *   2. Players join and deposit SOL
 *   3. Backend hashes the game result (SHA-256)
 *   4. Backend commits the hash + winner on-chain
 *   5. Backend settles the pot (escrow -> winner)
 *
 * Usage:
 *   npx ts-node scripts/settle-game.ts
 *
 * Requires:
 *   - Local validator running (`solana-test-validator`)
 *   - Program deployed (`anchor deploy`)
 *   - AUTHORITY_KEYPAIR env var or ~/.config/solana/id.json
 */

import * as anchor from '@coral-xyz/anchor';
import { Program } from '@coral-xyz/anchor';
import { PublicKey, Keypair, SystemProgram, LAMPORTS_PER_SOL } from '@solana/web3.js';
import { createHash } from 'crypto';

// ─── IDL type (generated by `anchor build`) ──────────────────────────────────
// After `anchor build`, import the actual IDL:
//   import { Goldenflop } from '../target/types/goldenflop';
// For now we use `any` as a placeholder.
type Goldenflop = any;

const PROGRAM_ID = new PublicKey('F1opGoldenFLop111111111111111111111111111');

// ─── Helpers ─────────────────────────────────────────────────────────────────

/** Derive the Game PDA from authority + game_id */
function deriveGamePDA(authority: PublicKey, gameId: bigint): [PublicKey, number] {
  const gameIdBuf = Buffer.alloc(8);
  gameIdBuf.writeBigUInt64LE(gameId);
  return PublicKey.findProgramAddressSync(
    [Buffer.from('game'), authority.toBuffer(), gameIdBuf],
    PROGRAM_ID,
  );
}

/** Hash a game result object using SHA-256 (deterministic JSON) */
function hashGameResult(result: object): Buffer {
  // IMPORTANT: Use a canonical/deterministic serialization.
  // JSON.stringify with sorted keys ensures consistency.
  const canonical = JSON.stringify(result, Object.keys(result).sort());
  return createHash('sha256').update(canonical).digest();
}

// ─── Main flow ──────────────────────────────────────────────────────────────

async function main() {
  // --- Setup provider ---
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  // The backend authority keypair (signs create_game, commit, settle)
  const authority = provider.wallet as anchor.Wallet;
  console.log('Authority:', authority.publicKey.toBase58());

  // Load program (after `anchor build`, use the generated IDL)
  const idl = await Program.fetchIdl(PROGRAM_ID, provider);
  if (!idl) throw new Error('IDL not found — run `anchor build` and deploy first');
  const program = new Program<Goldenflop>(idl, provider);

  // --- 1. Create game ---
  const gameId = BigInt(Date.now());
  const [gamePDA] = deriveGamePDA(authority.publicKey, gameId);
  console.log(`\n--- Creating game ${gameId} ---`);
  console.log('Game PDA (escrow):', gamePDA.toBase58());

  await program.methods
    .createGame(new anchor.BN(gameId.toString()))
    .accounts({
      authority: authority.publicKey,
      game: gamePDA,
      systemProgram: SystemProgram.programId,
    })
    .rpc();
  console.log('Game created.');

  // --- 2. Players join (deposit SOL) ---
  // In production, each player signs their own join_game tx from their wallet.
  // For demo, we create two funded keypairs.
  const player1 = Keypair.generate();
  const player2 = Keypair.generate();

  // Airdrop SOL to players (localnet/devnet only)
  for (const player of [player1, player2]) {
    const sig = await provider.connection.requestAirdrop(
      player.publicKey,
      2 * LAMPORTS_PER_SOL,
    );
    await provider.connection.confirmTransaction(sig);
  }

  const buyIn = 0.5 * LAMPORTS_PER_SOL; // 0.5 SOL each

  console.log(`\n--- Player 1 joining (${player1.publicKey.toBase58().slice(0, 8)}...) ---`);
  await program.methods
    .joinGame(new anchor.BN(buyIn))
    .accounts({
      player: player1.publicKey,
      game: gamePDA,
      systemProgram: SystemProgram.programId,
    })
    .signers([player1])
    .rpc();

  console.log(`--- Player 2 joining (${player2.publicKey.toBase58().slice(0, 8)}...) ---`);
  await program.methods
    .joinGame(new anchor.BN(buyIn))
    .accounts({
      player: player2.publicKey,
      game: gamePDA,
      systemProgram: SystemProgram.programId,
    })
    .signers([player2])
    .rpc();

  // Verify escrow balance
  const escrowBalance = await provider.connection.getBalance(gamePDA);
  console.log(`Escrow pot balance: ${escrowBalance / LAMPORTS_PER_SOL} SOL`);

  // --- 3. Game plays out off-chain, backend produces result ---
  const gameResult = {
    gameId: gameId.toString(),
    players: [
      { wallet: player1.publicKey.toBase58(), startChips: buyIn, endChips: 0, actions: ['call', 'raise', 'call'] },
      { wallet: player2.publicKey.toBase58(), startChips: buyIn, endChips: buyIn * 2, actions: ['call', 'call', 'call'] },
    ],
    communityCards: ['Ah', 'Kd', '7s', '2c', '9h'],
    winner: player2.publicKey.toBase58(),
    potSize: buyIn * 2,
    timestamp: Date.now(),
  };

  // --- 4. Hash the result ---
  const resultHashBuf = hashGameResult(gameResult);
  const resultHash = Array.from(resultHashBuf); // [u8; 32]
  console.log(`\n--- Committing result hash ---`);
  console.log('Hash (hex):', resultHashBuf.toString('hex'));
  console.log('Winner:', player2.publicKey.toBase58());

  // --- 5. Commit hash + winner on-chain ---
  await program.methods
    .commitResultHash(resultHash, player2.publicKey)
    .accounts({
      authority: authority.publicKey,
      game: gamePDA,
    })
    .rpc();
  console.log('Result hash committed on-chain.');

  // --- 6. Settle pot ---
  console.log(`\n--- Settling pot ---`);
  const winnerBalanceBefore = await provider.connection.getBalance(player2.publicKey);

  await program.methods
    .settlePot()
    .accounts({
      authority: authority.publicKey,
      game: gamePDA,
      winner: player2.publicKey,
    })
    .rpc();

  const winnerBalanceAfter = await provider.connection.getBalance(player2.publicKey);
  console.log(
    `Winner balance: ${winnerBalanceBefore / LAMPORTS_PER_SOL} -> ${winnerBalanceAfter / LAMPORTS_PER_SOL} SOL`,
  );
  console.log(`Payout: +${(winnerBalanceAfter - winnerBalanceBefore) / LAMPORTS_PER_SOL} SOL`);

  // --- 7. Verify on-chain state ---
  const gameAccount = await program.account.game.fetch(gamePDA);
  console.log(`\n--- On-chain verification ---`);
  console.log('Status:', Object.keys(gameAccount.status)[0]); // "settled"
  console.log('Result hash:', Buffer.from(gameAccount.resultHash).toString('hex'));
  console.log('Settled amount:', gameAccount.settledAmount.toString(), 'lamports');
  console.log('Pot remaining:', gameAccount.pot.toString(), 'lamports');

  // --- 8. Anyone can verify the result ---
  // Given the full gameResult JSON, anyone can:
  const verifyHash = hashGameResult(gameResult);
  const onChainHash = Buffer.from(gameAccount.resultHash);
  console.log(`\n--- Public verification ---`);
  console.log('Computed hash matches on-chain:', verifyHash.equals(onChainHash));

  console.log('\nDone!');
}

main().catch(console.error);
