-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "isPractice" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tokenMint" TEXT NOT NULL DEFAULT 'SOL',
ADD COLUMN     "turnTimeoutMs" INTEGER NOT NULL DEFAULT 30000;
